name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))"
    steps:
    - uses: actions/checkout@v2.2.0
    - uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: '17' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
    - run: |
          chmod +x ./gradlew
          chmod +x ./curse_upload
          ./gradlew build
          ./curse_upload
      env:
        CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/
